// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:5a2ce174-b1da-46be-b5ef-d8e4bee83935",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_3o3HPdFNJ",
    "aws_user_pools_web_client_id": "6hnqfubc8vdftmbdcuvjsvpog3"
};


export default awsmobile;
