// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "ngbaseapp-20181214131150-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://ngbaseapp-20181214131150-hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:084b4d54-cf20-4969-afb5-eb5d1ef72ee0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_MAgEOTNtG",
    "aws_user_pools_web_client_id": "6b4ej34hfucbkjs44a07hueopv"
};


export default awsmobile;
