// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "ngbaseapp-20181213135723-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://ngbaseapp-20181213135723-hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:dfd7bf7e-b0c4-491e-84bc-d09d7cc1e85e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_5uz7k5YwV",
    "aws_user_pools_web_client_id": "4kht4egass0kikh7plvhm4qp2h"
};


export default awsmobile;
